version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
